name: seed_ci_pipeline

on:
  pull_request:
    types:
      - labeled

jobs:
  seed_job:
    name: 'Check the Pull Request is labeled correctly'
    if: github.event.label.name == 'seed'
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.3
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'seed_s3'
        
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.3
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'seed_s3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.3
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: 'seed_s3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}